[project]
name = "projekt-rechenrally"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.1.0",
    "click>=8.1.8",
    "inkex>=1.4.1",
    "lxml>=5.3.0",
    "pytest>=8.3.5",
    "tool>=0.8.0",
]
