[project]
name = "projekt-rechenrally"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.8",
    "lxml>=5.3.0",
]
